// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgbroker

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TaskqMessage struct {
	SortKey       int64
	ID            string
	Queue         string
	Payload       []byte
	Attempts      int32
	MaxRetry      int32
	EnqueuedAt    pgtype.Timestamptz
	LockedUntil   pgtype.Timestamptz
	ReceiptHandle pgtype.Text
}
