// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package pgbroker

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ackMessage = `-- name: AckMessage :execrows
DELETE FROM taskq_messages
WHERE id = $1 AND receipt_handle = $2
`

type AckMessageParams struct {
	TargetID            string
	TargetReceiptHandle pgtype.Text
}

// Removes the message this specific delivery refers to. Matching on both
// id and receipt_handle means a stale Ack from an expired, already-
// redelivered lease can't delete the row out from under whoever holds the
// current receipt — it deletes zero rows instead, and the caller can tell
// from the returned count.
func (q *Queries) AckMessage(ctx context.Context, arg AckMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, ackMessage, arg.TargetID, arg.TargetReceiptHandle)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const dequeueMessage = `-- name: DequeueMessage :one
WITH candidate AS (
    SELECT taskq_messages.sort_key
    FROM taskq_messages
    WHERE taskq_messages.queue = $3
      AND (taskq_messages.locked_until IS NULL OR taskq_messages.locked_until < now())
    ORDER BY taskq_messages.sort_key
        FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE taskq_messages m
SET locked_until = $1,
    receipt_handle = $2
FROM candidate
WHERE m.sort_key = candidate.sort_key
RETURNING m.id, m.queue, m.payload, m.attempts, m.max_retry, m.enqueued_at, m.receipt_handle
`

type DequeueMessageParams struct {
	NewLockedUntil   pgtype.Timestamptz
	NewReceiptHandle pgtype.Text
	TargetQueue      string
}

type DequeueMessageRow struct {
	ID            string
	Queue         string
	Payload       []byte
	Attempts      int32
	MaxRetry      int32
	EnqueuedAt    pgtype.Timestamptz
	ReceiptHandle pgtype.Text
}

// Finds the oldest available row for queue (unleased, or its lease
// expired), then atomically claims it by stamping locked_until and a
// fresh receipt_handle in the same statement. FOR UPDATE SKIP LOCKED lets
// concurrent Dequeue calls on other rows proceed instead of blocking on
// this one; the candidate CTE, not the outer UPDATE, is what SKIP LOCKED
// applies to.
//
// Named args deliberately don't reuse the column names they populate
// (target_queue vs. queue, new_locked_until vs. locked_until, …) — sqlc's
// parser treats an sqlc.arg() name that collides with an in-scope column
// as an ambiguous column reference, not a parameter. Columns inside the
// CTE are fully qualified for the same reason: once the outer statement is
// UPDATE ... FROM candidate, sqlc's analyzer treats bare column names in
// the CTE as ambiguous too.
func (q *Queries) DequeueMessage(ctx context.Context, arg DequeueMessageParams) (DequeueMessageRow, error) {
	row := q.db.QueryRow(ctx, dequeueMessage, arg.NewLockedUntil, arg.NewReceiptHandle, arg.TargetQueue)
	var i DequeueMessageRow
	err := row.Scan(
		&i.ID,
		&i.Queue,
		&i.Payload,
		&i.Attempts,
		&i.MaxRetry,
		&i.EnqueuedAt,
		&i.ReceiptHandle,
	)
	return i, err
}

const enqueue = `-- name: Enqueue :exec


INSERT INTO taskq_messages (id, queue, payload, attempts, max_retry, enqueued_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type EnqueueParams struct {
	ID         string
	Queue      string
	Payload    []byte
	Attempts   int32
	MaxRetry   int32
	EnqueuedAt pgtype.Timestamptz
}

// pgbroker/queries.sql
//
// Full query set for pgbroker. Grouped in three tiers:
//  1. Broker interface ops — Enqueue/Dequeue/Ack/Nack. These are the only
//     ones broker.go calls to satisfy taskq.Broker; everything else here
//     is optional tooling around it.
//  2. Notify — the LISTEN/NOTIFY wake-up used by blocking Dequeue.
//  3. Operational — queue depth, inspection, purge. Not part of the
//     Broker contract; useful for admin scripts, debugging, and tests
//     (e.g. taskqtest cleanup between subtests).
//
// =============================================================================
// 1. Broker interface ops
// =============================================================================
func (q *Queries) Enqueue(ctx context.Context, arg EnqueueParams) error {
	_, err := q.db.Exec(ctx, enqueue,
		arg.ID,
		arg.Queue,
		arg.Payload,
		arg.Attempts,
		arg.MaxRetry,
		arg.EnqueuedAt,
	)
	return err
}

const listQueues = `-- name: ListQueues :many
SELECT DISTINCT queue FROM taskq_messages ORDER BY queue
`

// Distinct queue names with at least one message. Handy for an admin
// dashboard or CLI that doesn't otherwise know what queues exist.
func (q *Queries) ListQueues(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listQueues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var queue string
		if err := rows.Scan(&queue); err != nil {
			return nil, err
		}
		items = append(items, queue)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nackDelete = `-- name: NackDelete :execrows
DELETE FROM taskq_messages
WHERE id = $1 AND receipt_handle = $2
`

type NackDeleteParams struct {
	TargetID            string
	TargetReceiptHandle pgtype.Text
}

// Same targeting as AckMessage. Nack is delete-then-reinsert (see
// NackReinsert) rather than an in-place UPDATE, because sort_key must
// advance to move the message to the back of the queue, and
// GENERATED ALWAYS AS IDENTITY only assigns a fresh value on INSERT. Run
// in the same transaction as NackReinsert.
func (q *Queries) NackDelete(ctx context.Context, arg NackDeleteParams) (int64, error) {
	result, err := q.db.Exec(ctx, nackDelete, arg.TargetID, arg.TargetReceiptHandle)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const nackReinsert = `-- name: NackReinsert :exec
INSERT INTO taskq_messages (id, queue, payload, attempts, max_retry, enqueued_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type NackReinsertParams struct {
	ID         string
	Queue      string
	Payload    []byte
	Attempts   int32
	MaxRetry   int32
	EnqueuedAt pgtype.Timestamptz
}

// Re-inserts the message with the caller-supplied Attempts (and every
// other field) persisted verbatim, per Broker.Nack's contract — pgbroker
// does not compute its own retry count. locked_until/receipt_handle are
// left NULL (unclaimed), and the fresh sort_key this INSERT generates is
// what puts it behind every message already waiting.
func (q *Queries) NackReinsert(ctx context.Context, arg NackReinsertParams) error {
	_, err := q.db.Exec(ctx, nackReinsert,
		arg.ID,
		arg.Queue,
		arg.Payload,
		arg.Attempts,
		arg.MaxRetry,
		arg.EnqueuedAt,
	)
	return err
}

const notifyQueue = `-- name: NotifyQueue :exec

SELECT pg_notify('taskq_new_message', $1::text)
`

// =============================================================================
// 2. Notify — powers blocking Dequeue without a hot-loop
// =============================================================================
// Wakes any Dequeue call currently blocked in WaitForNotification for this
// queue. Called after Enqueue and after NackReinsert commit (same
// transaction for Nack — Postgres only delivers NOTIFY if the transaction
// actually commits, so a rolled-back Nack never wakes anyone about a
// requeue that didn't happen).
func (q *Queries) NotifyQueue(ctx context.Context, targetQueue string) error {
	_, err := q.db.Exec(ctx, notifyQueue, targetQueue)
	return err
}

const peekMessages = `-- name: PeekMessages :many
SELECT id, queue, payload, attempts, max_retry, enqueued_at, locked_until, receipt_handle
FROM taskq_messages
WHERE queue = $1
ORDER BY sort_key
LIMIT $2
`

type PeekMessagesParams struct {
	TargetQueue string
	RowLimit    int32
}

type PeekMessagesRow struct {
	ID            string
	Queue         string
	Payload       []byte
	Attempts      int32
	MaxRetry      int32
	EnqueuedAt    pgtype.Timestamptz
	LockedUntil   pgtype.Timestamptz
	ReceiptHandle pgtype.Text
}

// Read-only inspection of the oldest N messages on queue — no FOR UPDATE,
// no claiming, no side effects. For debugging ("what's stuck in this
// queue"), not for consumption; use Dequeue for that.
func (q *Queries) PeekMessages(ctx context.Context, arg PeekMessagesParams) ([]PeekMessagesRow, error) {
	rows, err := q.db.Query(ctx, peekMessages, arg.TargetQueue, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PeekMessagesRow
	for rows.Next() {
		var i PeekMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Queue,
			&i.Payload,
			&i.Attempts,
			&i.MaxRetry,
			&i.EnqueuedAt,
			&i.LockedUntil,
			&i.ReceiptHandle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeAll = `-- name: PurgeAll :execrows
DELETE FROM taskq_messages
`

// Deletes every message in the table, across all queues. Same caveats as
// PurgeQueue, one level more destructive — intended for wiping a test
// database between full test runs, not for any runtime code path.
func (q *Queries) PurgeAll(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeAll)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeQueue = `-- name: PurgeQueue :execrows
DELETE FROM taskq_messages WHERE queue = $1
`

// Deletes every message on queue, claimed or not. Destructive — for test
// cleanup (e.g. taskqtest resetting state between subtests) or a deliberate
// admin action, never called from Broker's own code paths.
func (q *Queries) PurgeQueue(ctx context.Context, targetQueue string) (int64, error) {
	result, err := q.db.Exec(ctx, purgeQueue, targetQueue)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const queueDepth = `-- name: QueueDepth :one

SELECT count(*) FROM taskq_messages WHERE queue = $1
`

// =============================================================================
// 3. Operational — not part of taskq.Broker; admin/debugging/test tooling
// =============================================================================
// Total messages waiting on queue, claimed or not. Useful for monitoring
// and for tests asserting a queue drained to zero.
func (q *Queries) QueueDepth(ctx context.Context, targetQueue string) (int64, error) {
	row := q.db.QueryRow(ctx, queueDepth, targetQueue)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const queueDepthAvailable = `-- name: QueueDepthAvailable :one
SELECT count(*)
FROM taskq_messages
WHERE queue = $1
  AND (locked_until IS NULL OR locked_until < now())
`

// Messages on queue that are actually claimable right now (unleased, or
// lease expired) — excludes in-flight ones a consumer currently holds.
func (q *Queries) QueueDepthAvailable(ctx context.Context, targetQueue string) (int64, error) {
	row := q.db.QueryRow(ctx, queueDepthAvailable, targetQueue)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const reapExpiredLease = `-- name: ReapExpiredLease :execrows
UPDATE taskq_messages
SET locked_until = NULL, receipt_handle = NULL
WHERE queue = $1 AND locked_until < now()
`

// Manually clears an expired lease without claiming it, i.e. makes a
// crashed consumer's message immediately visible again instead of waiting
// for the next Dequeue to happen to find it. Not required for correctness
// — Dequeue's own WHERE clause already treats an expired lease as
// available — this is purely an operational nicety for an admin tool that
// wants to force it.
func (q *Queries) ReapExpiredLease(ctx context.Context, targetQueue string) (int64, error) {
	result, err := q.db.Exec(ctx, reapExpiredLease, targetQueue)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
